package com.joe.taskira.audit.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    USER_CREATED,
    TICKET_CREATED,
    TICKET_STATUS_CHANGED,
    PROJECT_CREATED,
    PROJECT_ARCHIVED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    USER_ROLE_CHANGED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    ATTACHMENT_CREATED,
    ATTACHMENT_DELETED
}
