ALTER TABLE users ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tickets ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
